### PR TITLE
Multi-byte reads

### PR DESCRIPTION
**Pull request by pepijndevos**
Very straightforward copy-paste of write that allows you to do something like 

```
uint8_t data[16];
fram.read(0, data, 16);
```

### CODE REVIEW

**Comment by jacky4566** [comment]
+1 looks good to me. Going to add into my copy.

**Comment by jacky4566** [comment]
Looks good to me. But i'm thinking maybe you should make it more user friendly. 
Do two functions. read16 and read32. Thus negating the need to convert a byte array to an int or float.

**Comment by pepijndevos** [comment]
The point is not just to read larger data types, but read whole arrays as well. IMO, a simple cast and a lot of flexibility outweighs the API clutter of having read/write functions for every possible data type.

**Comment by ladyada** [comment]
gr8!

**Pull request merged**
